# Site settings
title: Sieci urzÄ…dzeÅ„ mobilnych - PJATK
short_name: SUM - PJATK
description: >
  Sieci urzÄ…dzeÅ„ mobilnych to specjalizacja przy Polsko-JapoÅ„skiej Akademii
  Technik Komputerowych. Studenci specjalizacji majÄ… okazjÄ™ poznaÄ‡ nowe
  technologie w dziedzinie platform mobilnych - Android, iOS i Windows Phone.
theme_color: "#e51a26"
url: "https://sum.pja.edu.pl"
logo: "logo-pjatk.webp"
github_username: PJATK-SUM

exclude:
  - package*
  - webpack.config.js
  - Gemfile
  - README.md
  - node_module

# Build settings
markdown: kramdown

languages:
  pl: 
    title: ðŸ‡µðŸ‡± PL
    path: /
  en: 
    title: ðŸ‡¬ðŸ‡§ EN
    path: /en/

i18n:
  pl:
    specialization: Sieci urzÄ…dzeÅ„ <span>mobilnych</span>
    school: Polsko-JapoÅ„ska Akademia Technik Komputerowych
    menu:
      main: Strona gÅ‚Ã³wna
      about: O nas
      projects: Projekty studentÃ³w
      movies: Filmy
      contact: Kontakt
    hero: MyÅ›l globalnie, dziaÅ‚aj lokalnie
    about:
      title: Tematyka Specjalizacji
      description: >
        W trakcie trzech semestrÃ³w nauki na specjalizacji, studenci otrzymujÄ…
        praktycznÄ… wiedzÄ™ dotyczÄ…cÄ… tworzenia oprogramowania na platformy
        mobilne. ZdobywajÄ… informacje z zakresu: systemÃ³w operacyjnych oraz
        architektur sprzÄ™towych urzÄ…dzeÅ„ mobilnych...
      more_info: WiÄ™cej informacji
      more_info_close: Zamknij
      mobile: Platformy mobilne
      mobile_description: iOS, Android
      languages: JÄ™zyki programowania
      languages_description: Objective-C, Swift, Java, Kotlin, C#, Python
      collaboration:
        title: WspÃ³Å‚praca
        description: >
          Nasze projekty nie mogÅ‚y by istnieÄ‡ bez odpowienich czÄ™sci i elementÃ³w.
          Dlatego w ramach koÅ‚a naukowego naszej specjalizacji chetnie zawieramy
          wspÃ³Å‚prace z rÃ³Å¼nymi dostawcami.
        list:
          - <a href="https://botland.com.pl" target="_blank"><img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://botland.com.pl/img/logo_botland_kn.png" alt="Sklep dla robotykÃ³w i elektronikÃ³w, Arduino, Raspberry Pi - BOTLAND"/></a>
    labs:
      title: OPIS LABORATORIUM
      description: >
        Laboratorium specjalizacji podlega nieustannemu rozwojowi, aby
        nadÄ…Å¼aÄ‡ za dynamicznie zmieniajÄ…cym siÄ™ rynkiem urzÄ…dzeÅ„
        mobilnych. Inwestycje w infrastrukturÄ™ laboratorium finansowane
        sÄ… z grantÃ³w badawczych, funduszy statutowych oraz Å›rodkÃ³w
        wÅ‚asnych uczelni. Wsparcia udzielajÄ… teÅ¼ wspÃ³Å‚pracujÄ…ce ze
        specjalizacjÄ… firmy z branÅ¼y IT. Efektami tych staraÅ„ sÄ…
        pracownie:
      list:
        - title: 133
          description: >
            wyposaÅ¼ona w komputery iMac pozwalajÄ…ce tworzyÄ‡
            aplikacje dla platformy iOS w oparciu o jÄ™zyki Swift i
            ObjectiveC;
        - title: 132
          description: >
            wyposaÅ¼ona w komputery z ekranami dotykowymi,
            pozwalajÄ…ce tworzyÄ‡ aplikacje w architekturze Universal
            Windows Platform dla urzÄ…dzeÅ„ IoT, Mobile, PC a nawet
            HoloLens;
        - title: S-9
          description: >
            pole dziaÅ‚aÅ„ dla wszystkich projektÃ³w studenckich i
            naukowych jakie przychodzÄ… do gÅ‚owy naszym studentom
      devices_first:
        - Samsung Galaxy
        - Nexus
        - Apple iPhone, iPad
      devices_second:
        - kostki Dice+
        - Dell Venue 8
        - Oculus Rift
        - Raspberry Pi 3
        - MS Kinect
        - Hololens

    projects:
      title: Projekty studentÃ³w
      list:
        - name: PJATK Android
          image: /images/app-pjwstk-android.webp
          href: https://play.google.com/store/apps/details?id=com.pjwstk.mobile.dziekanat
          link: play.google.com
        - name: PJATK iOS
          image: /images/app-pjwstk-apple.webp
          href: https://itunes.apple.com/pl/app/pjwstk/id828657671?mt=8
          link: itunes.apple.com
    videos:
      title: Filmy
      list:
        - link: https://www.youtube-nocookie.com/watch?v=PzFccmeBddE
          title: Andrii Kovalchuk â€žBufferâ€
        - link: https://www.youtube-nocookie.com/watch?v=B9eN_6UQotc
          title: MichaÅ‚ Gutowski "Smart Home"
        - link: https://www.youtube-nocookie.com/watch?v=kITTL7_3pS8
          title: Kamil Kowalski "Wirtualny asystent studenta"
        - link: https://www.youtube-nocookie.com/watch?v=WEknAzWAxUY
          title: Kondrata Kielar "Dziekanat"
        - link: https://www.youtube-nocookie.com/watch?v=TKZ7I0vIaks
          title: Jakub Fryga o projekcie pomagajÄ…cym wykryÄ‡ chorobÄ™ Parkinsona
        - link: https://www.youtube-nocookie.com/watch?v=JghBwo_2V_s
          title: Mateusz Knop "Plan zajÄ™Ä‡"
        - link: https://www.youtube-nocookie.com/watch?v=8zg7UOzygos
          title: That's how we learn with Tomaszew
        - link: https://www.youtube-nocookie.com/watch?v=ErD1yJtX_-8
          title: Halloween 2015
        - link: https://www.youtube-nocookie.com/watch?v=Tr4-Gr-jsRg
          title: 3DprinterBuild
    contact:
      title: Kontakt
      address: >
        Polsko-JapoÅ„ska Akademia
        Technik Komputerowych<br>
        ul. Koszykowa 86<br>
        02-008 Warszawa
      phone_title: Telefon
      email_title: E-mail
      privacy: Polityka prywatnoÅ›ci
  en:
    specialization: <span>Mobile</span> networking
    school: Polish-Japanese Academy of Information Technology
    menu:
      main: Homepage
      about: About us
      projects: Students projects
      movies: Videos
      contact: Contact
    hero: Think globally, act locally
    about:
      title: Topics of Specialization
      description: >
        During the three semesters of study in the specialization, students receive
        practical knowledge of software development for mobile platforms
        mobile platforms. They gain information on: operating systems and
        hardware architectures of mobile devices....
      more_info: More information
      more_info_close: Zamknij
      mobile: Platformy mobilne
      mobile_description: Mobile platforms
      languages: Programming languages
      languages_description: Objective-C, Swift, Java, Kotlin, C#, Python
      collaboration:
        title: Collaboration
        description: >
          Our projects could not exist without the right parts and components.
          Therefore, within the framework of the scientific circle of our specialty, we are happy to enter into
          cooperation with various suppliers.
        list:
          - <a href="https://botland.com.pl" target="_blank"><img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://botland.com.pl/img/logo_botland_kn.png" alt="Store for robotics and electronics, Arduino, Raspberry Pi - BOTLAND"/></a>
    labs:
      title: LABORATORY DESCRIPTION
      description: >
        The specialization laboratory is undergoing continuous development to
        keep up with the rapidly changing market for mobile devices
        mobile devices. Investments in the laboratory's infrastructure are financed
        are from research grants, statutory funds and the university's
        wÅ‚asnych uczelni. Wsparcia udzielajÄ… teÅ¼ wspÃ³Å‚pracujÄ…ce ze
        specjalizacjÄ… firmy z branÅ¼y IT. Efektami tych staraÅ„ sÄ…
        studios:
      list:
        - title: 133
          description: >
            equipped with iMacs that allow the development of
            iOS platform applications based on Swift and
            ObjectiveC;
        - title: 132
          description: >
            equipped with computers with touch screens,
            allowing the development of applications on the Universal
            Windows Platform for IoT, Mobile, PC and even
            HoloLens;
        - title: S-9
          description: >
            field of action for all student and
            scientific projects that come to mind for our students
      devices_first:
        - Samsung Galaxy
        - Nexus
        - Apple iPhone, iPad
      devices_second:
        - cubes Dice+
        - Dell Venue 8
        - Oculus Rift
        - Raspberry Pi 3
        - MS Kinect
        - Hololens

    projects:
      title: Students projects
      list:
        - name: PJATK Android
          image: /images/app-pjwstk-android.webp
          href: https://play.google.com/store/apps/details?id=com.pjwstk.mobile.dziekanat
          link: play.google.com
        - name: PJATK iOS
          image: /images/app-pjwstk-apple.webp
          href: https://itunes.apple.com/pl/app/pjwstk/id828657671?mt=8
          link: itunes.apple.com
    videos:
      title: Videos
      list:
        - link: https://www.youtube-nocookie.com/watch?v=PzFccmeBddE
          title: Andrii Kovalchuk â€žBufferâ€
        - link: https://www.youtube-nocookie.com/watch?v=B9eN_6UQotc
          title: MichaÅ‚ Gutowski "Smart Home"
        - link: https://www.youtube-nocookie.com/watch?v=kITTL7_3pS8
          title: Kamil Kowalski "Wirtualny asystent studenta"
        - link: https://www.youtube-nocookie.com/watch?v=WEknAzWAxUY
          title: Kondrata Kielar "Dziekanat"
        - link: https://www.youtube-nocookie.com/watch?v=TKZ7I0vIaks
          title: Jakub Fryga o projekcie pomagajÄ…cym wykryÄ‡ chorobÄ™ Parkinsona
        - link: https://www.youtube-nocookie.com/watch?v=JghBwo_2V_s
          title: Mateusz Knop "Plan zajÄ™Ä‡"
        - link: https://www.youtube-nocookie.com/watch?v=8zg7UOzygos
          title: That's how we learn with Tomaszew
        - link: https://www.youtube-nocookie.com/watch?v=ErD1yJtX_-8
          title: Halloween 2015
        - link: https://www.youtube-nocookie.com/watch?v=Tr4-Gr-jsRg
          title: 3DprinterBuild
    contact:
      title: Kontakt
      address: >
        Polish-Japanese Academy
        of Information Technology<br>
        Koszykowa 86 st.<br>
        02-008 Warsaw
      phone_title: Phone
      email_title: E-mail
      privacy: Privacy Policy